### ISSUE TITLE
All requests start to fail with `TimeoutError`

### ISSUE THREAD

**Issue by jvstme** [nebius/pysdk#62]
The SDK works fine at first, but at some point all requests start to fail with `TimeoutError`. This seems to happen if the SDK was unused (i.e. there were no requests) for a few minutes.

There doesn't seem to be a fixed time period after which this happens, so the example below uses a progressively increasing timeout.

### Steps to reproduce

Set your credentials (either service account or access token) and run the script.

```python
from nebius.sdk import SDK
from nebius.api.nebius.compute.v1 import PlatformServiceClient, ListPlatformsRequest
from datetime import datetime
import time


sdk = SDK(
    service_account_private_key_file_name="/path/to/private/key",
    service_account_public_key_id="key-id-from-nebius-console",
    service_account_id="service-account-id-from-nebius-console",
)

def test():
    PlatformServiceClient(sdk).list(
        ListPlatformsRequest(parent_id="project-e00public-images"),
        timeout=15,
    ).wait()

for attempt in range(1, 10):
    print(datetime.now().isoformat(), "Attempt", attempt)
    test()
    sleep_for = attempt * 120 + 10
    print(datetime.now().isoformat(), "Success. Sleeping for", sleep_for, "seconds")
    time.sleep(sleep_for)
```

### Expected behavior

The script never fails.

### Actual behavior

At some point requests stop working and fail with `TimeoutError`.

```
2025-03-18T21:07:32.251793 Attempt 1
2025-03-18T21:07:32.830989 Success. Sleeping for 130 seconds
2025-03-18T21:09:42.831403 Attempt 2
2025-03-18T21:09:42.919351 Success. Sleeping for 250 seconds
2025-03-18T21:13:52.934049 Attempt 3
2025-03-18T21:13:53.019125 Success. Sleeping for 370 seconds
2025-03-18T21:20:03.020362 Attempt 4
Traceback (most recent call last):
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 374, in __await__
    res = yield from self._await_result().__await__()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 367, in _await_result
    return await self._future
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 335, in _retry_loop
    ret = await self._call  # type: ignore[unused-ignore]
          ^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/grpc/aio/_interceptor.py", line 472, in __await__
    response = yield from call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/grpc/aio/_call.py", line 308, in __await__
    response = yield from self._call_response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/repro/repro.py", line 21, in <module>
    test()
    ~~~~^^
  File "/tmp/repro/repro.py", line 17, in test
    ).wait()
      ~~~~^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 201, in wait
    return self._channel.run_sync(self, timeout=self._timeout)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/channel.py", line 286, in run_sync
    return self._event_loop.run_until_complete(wait_for(awaitable, timeout))
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

While not shown in this example, `TimeoutError` does not only apply to a single request. All requests start to fail and the SDK doesn't recover until the program is restarted.

### Environment

```shell
> python --version
Python 3.13.1
> pip freeze
certifi==2025.1.31
cffi==1.17.1
cryptography==44.0.2
googleapis-common-protos==1.69.2
grpcio==1.71.0
grpcio-status==1.71.0
nebius==0.2.14
protobuf==5.29.3
pycparser==2.22
PyJWT==2.10.1
```

Also tested on the `main` branch, commit `a73257c`.

**Comment by complynx** [comment]
Reproduced on the same version of python. Python 3.10 — couldn't reproduce.
Looking into it

**Comment by jvstme** [comment]
@complynx, I've seen this problem on Python 3.10 as well. Sometimes you have to wait longer to reproduce, it takes an arbitrary amount of time.
Thank you for looking into this

**Comment by complynx** [comment]
This issue is valid only when API is used synchronously.
I just posted a proposed solution that might help

**Comment by jvstme** [comment]
@complynx, I think I'm still seeing a similar error on branch `PUBLICAPI-650_proposed_fix_for_issue_62`:
```
2025-03-19T15:05:22.928700 Attempt 1
2025-03-19T15:05:24.557865 Success. Sleeping for 250 seconds
2025-03-19T15:09:34.558447 Attempt 2
2025-03-19T15:09:34.659619 Success. Sleeping for 490 seconds
2025-03-19T15:17:44.669244 Attempt 3
Traceback (most recent call last):
  File "/tmp/repro/repro.py", line 21, in <module>
    test()
    ~~~~^^
  File "/tmp/repro/repro.py", line 17, in test
    ).wait()
      ~~~~^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 201, in wait
    return self._channel.run_sync(self, timeout=self._timeout)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/channel.py", line 317, in run_sync
    return self._event_loop.run_until_complete(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _run_awaitable_with_timeout(awaitable, timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/channel.py", line 177, in _run_awaitable_with_timeout
    if task.exception() is not None:
       ~~~~~~~~~~~~~~^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/channel.py", line 156, in wrap
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 373, in __await__
    res = yield from self._await_result().__await__()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 366, in _await_result
    return await self._future
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py", line 332, in _retry_loop
    ret = await self._call  # type: ignore[unused-ignore]
          ^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/grpc/aio/_interceptor.py", line 472, in __await__
    response = yield from call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/venv/lib64/python3.13/site-packages/grpc/aio/_call.py", line 308, in __await__
    response = yield from self._call_response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

**Comment by complynx** [comment]
Fixed the error wrappers, now it should properly throw a RequestError of type DEADLINE_EXCEEDED

**Comment by complynx** [comment]
If you will pass these errors, then it should work with next requests properly

**Comment by jvstme** [comment]
@complynx, can you please clarify what DEADLINE_EXCEEDED is and how it should be handled? I updated the script to ignore these errors, but the SDK still doesn't seem to recover - all requests following the first DEADLINE_EXCEEDED also fail with DEADLINE_EXCEEDED.

```
2025-03-19T17:55:19.213123 Attempt 1
2025-03-19T17:55:20.881015 Success
2025-03-19T17:55:20.881070 Sleeping for 240 seconds
2025-03-19T17:59:20.881312 Attempt 2
2025-03-19T17:59:20.970815 Success
2025-03-19T17:59:20.970864 Sleeping for 480 seconds
2025-03-19T18:07:20.989115 Attempt 3
2025-03-19T18:08:21.005992 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-19T18:08:21.006088 Sleeping for 20 seconds
2025-03-19T18:08:41.006240 Attempt 4
2025-03-19T18:09:41.014893 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-19T18:09:41.014957 Sleeping for 20 seconds
2025-03-19T18:10:01.015102 Attempt 5
2025-03-19T18:11:01.018896 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-19T18:11:01.018966 Sleeping for 20 seconds
2025-03-19T18:11:21.019403 Attempt 6
2025-03-19T18:12:21.024137 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
...
(and so on)
```

Tested on the latest main branch, commit c6f0d7f.

<details> 
<summary>Updated script</summary>

```python
from nebius.sdk import SDK
from nebius.api.nebius.compute.v1 import PlatformServiceClient, ListPlatformsRequest
from datetime import datetime
import time


sdk = SDK(
    service_account_private_key_file_name="/path/to/private/key",
    service_account_public_key_id="key-id-from-nebius-console",
    service_account_id="service-account-id-from-nebius-console",
)

def test():
    PlatformServiceClient(sdk).list(
        ListPlatformsRequest(parent_id="project-e00public-images"),
        timeout=60,
    ).wait()

success_count = 0

for attempt in range(1, 20):
    print(datetime.now().isoformat(), "Attempt", attempt)
    try:
        test()
    except Exception as e:
        print(datetime.now().isoformat(), "Error:", e)
        success_count = 0
        sleep_for = 20
    else:
        print(datetime.now().isoformat(), "Success")
        success_count += 1
        sleep_for = success_count * 240
    print(datetime.now().isoformat(), "Sleeping for", sleep_for, "seconds")
    time.sleep(sleep_for)
```

</details>

**Comment by complynx** [comment]
DEADLINE_EXCEEDED means, that the timeout was reached while performing the request.

**Comment by complynx** [comment]
Can you provide, please, the log with `logging.basicConfig(level=logging.DEBUG)`? You may be willing to also send logs to a file.

**Comment by jvstme** [comment]
@complynx, sure:

<details> 
  <summary>Debug log</summary>

```
DEBUG:nebius.base.service_account.pk_file:reading SA from file /tmp/repro/key.pem
2025-03-21T15:30:24.690516 Attempt 1
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:nebius.base.resolver:conventional resolver nebius.compute.v1.PlatformService resolved to compute.{domain}
DEBUG:nebius.base.resolver:template expander nebius.compute.v1.PlatformService resolved to compute.api.eu.nebius.cloud:443
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998378753662.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998378753662
DEBUG:nebius.aio.token.renewable:no refresh task yet, starting it
DEBUG:nebius.aio.token.renewable:renewal required, timeout 59.99998378753662
DEBUG:nebius.aio.token.renewable:refresh task started
DEBUG:nebius.aio.token.renewable:refreshing token, attempt 1
DEBUG:nebius.base.service_account.service_account:creating ExchangeTokenRequest for service account
DEBUG:nebius.aio.token.exchangeable:fetching new token, attempt: 1, timeout: 5.0
DEBUG:nebius.base.resolver:conventional resolver nebius.iam.v1.TokenExchangeService resolved to tokens.iam.{domain}
DEBUG:nebius.base.resolver:template expander nebius.iam.v1.TokenExchangeService resolved to tokens.iam.api.eu.nebius.cloud:443
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Calling b'/nebius.iam.v1.TokenExchangeService/Exchange', authentication is disabled
DEBUG:nebius.aio.token.exchangeable:token fetched: ne1...7DQ, expires in: 43200 seconds.
DEBUG:nebius.aio.token.renewable:received new token: ne1...7DQ, expires in 2025-03-22 02:30:24.705054+00:00
DEBUG:nebius.aio.token.renewable:Will refresh token after 38879.7705414 seconds, renewal attempt number 0
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
DEBUG:nebius.aio.channel:Canceling pending task <Task pending name='Timer for f=Request(.nebius.compute.v1.PlatformService.List, UnfinishedRequestStatus.INITIALIZED)' coro=<sleep() running at /usr/lib64/python3.13/asyncio/tasks.py:718> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-03-21T15:30:25.228996 Success
2025-03-21T15:30:25.229035 Sleeping for 240 seconds
2025-03-21T15:34:25.229227 Attempt 2
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99997687339783.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99997687339783
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
DEBUG:nebius.aio.channel:Canceling pending task <Task pending name='Timer for f=Request(.nebius.compute.v1.PlatformService.List, UnfinishedRequestStatus.INITIALIZED)' coro=<sleep() running at /usr/lib64/python3.13/asyncio/tasks.py:718> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-03-21T15:34:25.313182 Success
2025-03-21T15:34:25.313203 Sleeping for 480 seconds
2025-03-21T15:42:25.313343 Attempt 3
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998331069946.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998331069946
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
2025-03-21T15:43:25.318546 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-21T15:43:25.318583 Sleeping for 20 seconds
2025-03-21T15:43:45.318960 Attempt 4
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998688697815.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998688697815
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
DEBUG:nebius.aio.channel:Canceling pending task <Task pending name='Task for f=Request(.nebius.compute.v1.PlatformService.List, UnfinishedRequestStatus.INITIALIZED)' coro=<_wrap_awaitable.<locals>.wrap() running at /tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/channel.py:156> wait_for=<Task pending name='Task-19' coro=<Request._retry_loop() running at /tmp/repro/venv/lib64/python3.13/site-packages/nebius/aio/request.py:357> wait_for=<Task pending name='Task-21' coro=<UnaryUnaryCall._invoke() running at /tmp/repro/venv/lib64/python3.13/site-packages/grpc/aio/_call.py:586> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup()]> cb=[Task.task_wakeup()]>>
2025-03-21T15:44:45.324995 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-21T15:44:45.325090 Sleeping for 20 seconds
2025-03-21T15:45:05.325518 Attempt 5
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998354911804.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998354911804
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
2025-03-21T15:46:05.329448 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-21T15:46:05.329502 Sleeping for 20 seconds
2025-03-21T15:46:25.329671 Attempt 6
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998927116394.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998927116394
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
2025-03-21T15:47:25.333942 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-21T15:47:25.334001 Sleeping for 20 seconds
2025-03-21T15:47:45.334367 Attempt 7
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998331069946.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998331069946
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
2025-03-21T15:48:45.338453 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
2025-03-21T15:48:45.338516 Sleeping for 20 seconds
2025-03-21T15:49:05.338893 Attempt 8
DEBUG:nebius.aio.idempotency:added idempotency key to metadata
DEBUG:nebius.aio.authorization.interceptor:Authentication for b'/nebius.compute.v1.PlatformService/List' is enabled, auth_type=None
DEBUG:nebius.aio.authorization.interceptor:Authenticating b'/nebius.compute.v1.PlatformService/List', attempt=1, timeout=59.99998378753662.
DEBUG:nebius.aio.token.renewable:token fetch requested, attempt: 1,timeout: 59.99998378753662
DEBUG:nebius.aio.authorization.interceptor:Calling authenticated b'/nebius.compute.v1.PlatformService/List'.
2025-03-21T15:50:05.342362 Error: Request error DEADLINE_EXCEEDED: Deadline Exceeded
```

</details>

**Comment by complynx** [comment]
Can't reproduce. I suggest maybe connecting in the upcoming week using Zoom and look at the issue using some kind of debugger. I presume, the issue is heavily related to your environment or something.
Telegram t.me/complynx may be good for arranging the meeting. Or e-mail.

**Comment by jvstme** [comment]
> the issue is heavily related to your environment

You are right, I tried testing in different environments and get different results.

- Linux machine on my network - get DEADLINE_EXCEEDED after a few minutes of inactivity, all next requests also get DEADLINE_EXCEEDED (see [above](https://github.com/nebius/pysdk/issues/62#issuecomment-2737494634)).
- Docker container on the same Linux machine - same as above.
- Mac machine on the same network - get DEADLINE_EXCEEDED after a few minutes of inactivity, but next requests work as expected.
- Same Linux machine with a VPN - can't reproduce.
- A few different cloud VMs - can't reproduce.

@complynx, I will contact you soon so we can discuss the next steps

**Comment by complynx** [comment]
Fix in the #69
